### PR TITLE
Implemented 1.19.4

### PR DESCRIPTION
**Pull request by milutinke**
Base implementation of 1.19.4
Did only light testing, I need people who are willing to test it out properly, I do not have the time right now.

Entity, Block and Item palettes will be updated after thoroughly testing.

PS:
I had to look at the game code and do manual testing in order to get it working, since there is no info on the Wiki.vg
Some things might be slow to fix due to having to dig into the source code.

### CODE REVIEW

**Comment by Splarkszter** [comment]
What are the requirements of "test it out **properly**"?

**Comment by milutinke** [comment]
Added Item, Entity and Block palettes, Movement and Inventory work, while Entity handling is disabled until I figure out the changes with Entity Meta Data.

**Comment by ReinforceZwei** [comment]
Regarding Entity Meta Data, how about creating a new palette to store type value for each version that has change? It got a bit messy now after couple of versions.

For example, just like packet palette,
```c#
enum MetaDataType
{
    Byte,
    Varint,
    ...
}
```
```c#
// MetaDataTypePalette1194
{ 0, MetaDataType.Byte },
{ 1, MetaDataType.Varint },
...
```

**Comment by ghostdevv** [comment]
Been running a build of this pr overnight and haven't had any issues at all :heart:

**Comment by milutinke** [comment]
> Been running a build of this pr overnight and haven't had any issues at all heart

Awesome, glad to hear that.

**Comment by milutinke** [comment]
@ReinforceZwei I've added Entity Metadata Palettes, although they are not used yet.
So, if you have some time, you could wire them up and extract some logic for reading fields to separate methods, because in different versions they might differ.
I have also left links to the wiki pages with changes, although more work is needed to check everything.

**Comment by ReinforceZwei** [comment]
@milutinke Just want to let you know that I am working on the entity metadata part :)

**Comment by milutinke** [comment]
> @milutinke Just want to let you know that I am working on the entity metadata part :)

You can take my changes and commit to my repo, then I'll merge here, I did particles in a separate method, testing right now.

**Comment by ReinforceZwei** [comment]
Yup, I am doing on top of your work. I will push my code directly to this PR.

**Comment by ReinforceZwei** [comment]
After comparing the palettes with [minecraft-data](https://github.com/PrismarineJS/minecraft-data), I found that it actually doesn't need that much palettes. 1.13 - 1.19.2 can share one palette, and same with 1.9 to 1.12.2. I have cleaned they up and they _should_ work, I think. (missing an efficient way to test it)

For now, only the palette for 1.8 is not yet finished. Except that, I think all changes has been implemented for 1.19.4 to work.

**Comment by milutinke** [comment]
If we can do Metadata for 1.8, I can merge this: https://github.com/milutinke/Minecraft-Console-Client/tree/1.8-inv2

**Comment by ReinforceZwei** [comment]
Looks great, I will continue to work on 1.8 metadata palette and read method in the next few days.

**Comment by ReinforceZwei** [comment]
Shall we release the 1.19.4 first for people to _test_ it for us? 1.8 metadata can be implemented in a separate PR.

**Comment by milutinke** [comment]
> Shall we release the 1.19.4 first for people to _test_ it for us? 1.8 metadata can be implemented in a separate PR.

I agree, we could release it as a pre-release.

**Comment by milutinke** [comment]
Tested on 1.13, 1.14.3, 1.14.4, 1.15, 1.16.5, 1.17, 1.17.1, 1.18.2, 1.19.3, 1.19.4
Fixed a crash on 1.14.X and 1.15.X
Ready for merge, I'll merge it and mark as pre-release.
It needs real world testing, I did basic bare bones testing of chat and entities and particles.

**Pull request merged**
