### PR TITLE
DigBlock AntiCheat Error Fix

### PR DESCRIPTION
**Pull request by Nekiplay**

### CODE REVIEW

**Comment by Nekiplay** [comment]
I most likely copied an old version, expect an update

**Comment by Nekiplay** [comment]
If anything, the problem is that now breaking the block is sent from the bottom, and if the player is on top of the block being broken and he breaks it from below, the antichit does not allow to break the block.

**Comment by Nekiplay** [comment]
Kinda ready for cojones since I haven't found any comites breaking it.

**Comment by ReinforceZwei** [comment]
Your forked repository is outdated. Please update your fork before opening PR.

**Pull request closed without merging**
