### PR TITLE
Added dutch

### PR DESCRIPTION
**Pull request by br0gio**
I only did messages from MCC itself for now, I'll do the rest some other day.

### CODE REVIEW

**Comment by milutinke** [comment]
Thank you for your contribution.
Can you please add the missing keys from this branch and translate them: https://github.com/MCCTeam/Minecraft-Console-Client/blob/brucechen-toml-config/MinecraftClient/Resources/lang/en.ini
That is a pre-release branch which will be merged soon.

**Comment by BruceChenQAQ** [comment]
Now it has been merged.

We have added documentation on how to add translations, see: https://mccteam.github.io/guide/contibuting.html#translations

**Comment by milutinke** [comment]
Any plans to continue working on this?

**Comment by BruceChenQAQ** [comment]
Since translation in Crowdin is now supported, I will close this pull request.
All submitted translations have been imported into Crowdin.
Thank you for your contribution.

**Pull request closed without merging**
