### PR TITLE
Fix automated build for .NET releases

### PR DESCRIPTION
**Pull request by breadbyte**

### CODE REVIEW

**Comment by ReinforceZwei** [comment]
Could you also update the readme `Building from source` section for .NET 6?

**Comment by breadbyte** [comment]
Updated the README file. Needs review.

Verified that the build action works on my own fork, and that the manual build instructions are correct.

Since it is currently configured as a single file application, should we skip bundling the `.pdb` files and just put the executable files themselves as a release?
Keeping them zipped is beneficial though, it reduces the total download size from ~27mb (windows executable) to only ~8mb (zip)

Currently osx/mac releases are not built, should we add it as well?

image

**Comment by ReinforceZwei** [comment]
> should we skip bundling the .pdb files and just put the executable files themselves as a release?

I think those files should be hide from user, either not include them in the zip file or embed them in the exe file.

> Currently osx/mac releases are not built, should we add it as well?

Sure.

**Comment by ORelio** [comment]
Thanks for your work! 👍 (sorry for taking this long to review your PR)

**Comment by ORelio** [comment]
Just noticed that the automated build for Windows has no Exe icon. Apart from that, it works 🙂

**Comment by breadbyte** [comment]
I'm honestly a bit torn about whether to commit this PR due to #2082 being a devastating bug that I'm still trying to get to the root of.


> Just noticed that the automated build for Windows has no Exe icon. Apart from that, it works 🙂

Noted. I'll try and figure something out.

**Pull request merged**
