### PR TITLE
Added a /reload command for reloading the settings.

### PR DESCRIPTION
**Pull request by milutinke**
Added a /reload command for reloading the settings.
**NOTE: I've only tested some changes on a local server, haven't tested all Chat Bots, I need more people to test out chat bots with the `/reload` command.**

To test, you can clone my branch with the following command:
```bash
git clone https://github.com/milutinke/Minecraft-Console-Client --recursive -b reload-config
```

Here you can find out how to install Git and how to build the project from the source (Make sure to use my clone command above, not the documentation one): https://mccteam.github.io/docs/guide/installation.html#building-from-the-source-code

### CODE REVIEW

**Comment by milutinke** [comment]
Is it maybe better to unload all bots and load them again?

**Comment by ORelio** [comment]
Nice work! It would likely not be as reliable as a true restart but could come handy.
How about calling `OnSettingsReloaded()` when initializing the bot to avoid duplicating code?
(I'd suggest `OnSettingsReload` for the event name)

**Comment by milutinke** [comment]
> Nice work! It would likely not be as reliable as a true restart but could come handy. How about calling `OnSettingsReloaded()` when initializing the bot to avoid duplicating code? (I'd suggest `OnSettingsReload` for the event name)

In most of the bots I have a separate method Setup which I use in Initialize and OnSettingsReloaded, so there is no need in calling it, also in some bots I need to do a check if they've been disabled, which would be redundant on `Initialize`.
I'll rename the method.

**Comment by milutinke** [comment]
I've added a possibility to hard reload bots using `/reload hard`, this will first unload all bots, then load enabled ones, and then it will call `AfterGameJoined` on all of them if the client is still connected.

**Comment by milutinke** [comment]
Added a command to list loaded bots and to unload a specific bot or all bots.

**Comment by milutinke** [comment]
Can someone test this on a live server and report if everything is working fine, I currently don't have much time.

Manual on how to build yourself: https://mccteam.github.io/docs/guide/installation.html#building-from-the-source-code

Just use this command to clone my repo and branch instead the one from the documentation:
```bash
git clone https://github.com/milutinke/Minecraft-Console-Client --recursive -b eload-config
```

**Comment by milutinke** [comment]
Testing (Checked tested and works):
- [x] Alerts 
- [x] Auto Attack
- [x] Anti AFK
- [x] Auto Craft
- [x] Auto Eat
- [x] Auto Drop
- [x] Auto Respond
- [x] Replay Mod (soft reload)
- [x] Remote Control

- Disabled hard reloading due to crashing:
- [x] Replay Mod

- Couldn't test:
- Mailer
- Fishing Bot

**Comment by milutinke** [comment]
Opening a new PR.

**Pull request closed without merging**
