### PR TITLE
I translated it in french

### PR DESCRIPTION
**Pull request by goldenlib**
Because this is the only language that I know a bit

### CODE REVIEW

**Comment by ORelio** [comment]
Bravo ! Good work! Given the amount of lines to translate, that must have taken quite some time 👏

I've read through your translation file and made some improvements (clarify the meaning of some messages, fix some typos...).
Also made some changes to the English translation to backport some improvements made on the French translation.

As I may have introduced some mistakes myself, do not hesitate to read through and discuss my changes.
Another proofreader would also be welcome on this! 😄

**Comment by goldenlib** [comment]
It took me 3 days so it's possible that i made some mistakes. At least there is something now.

**Comment by ORelio** [comment]
I'll leave the PR open for a week in case someone can help us proofreading this translation.

**Comment by ORelio** [comment]
Ok, it's been a week so let's keep it as is. Thanks again for you contribution 🙂

**Pull request merged**
