### PR TITLE
Fix prevent AntiCheat Block Breaking (In Scripts)

### PR DESCRIPTION
**Pull request by Nekiplay**
- [x]  Fixed block breaking for anticheats in custom scripts
- [x] Added auxiliary methods for Direction

### CODE REVIEW

**Comment by Nekiplay** [comment]
Ready for review

**Comment by milutinke** [comment]
Looks good.
Also what is preventing you from porting that `getDirection` method to the MCC?
If it's the `mc.player.GetEyeHeight`, the eye height is `1.62` blocks high, so it can be hardcoded.

**Comment by Nekiplay** [comment]
> Looks good. Also what is preventing you from porting that `getDirection` method to the MCC? If it's the `mc.player.GetEyeHeight`, the eye height is `1.62` blocks high, so it can be hardcoded. Also, where is that method from by the way?

getDirection method from Meteor Client
GetHorizontalFacing from Minecraft Code

**Comment by milutinke** [comment]
> > Looks good. Also what is preventing you from porting that `getDirection` method to the MCC? If it's the `mc.player.GetEyeHeight`, the eye height is `1.62` blocks high, so it can be hardcoded. Also, where is that method from by the way?
> 
> getDirection I probably won't reschedule. getDirection method from Meteor Client GetHorizontalFacing from Minecraft Code

Does this work as is without getDirection method?

**Comment by Nekiplay** [comment]
> Does this work as is without getDirection method?

yes

**Comment by milutinke** [comment]
> > Does this work as is without getDirection method?
> 
> yes

Alright, thanks, I'll merge it.

**Pull request merged**
