### PR TITLE
Fix all warnings & Trim

### PR DESCRIPTION
**Pull request by BruceChenQAQ**
Removed DotNetZip from the source code and got it from NuGet instead.
Because its target version is too low results in a large number of warnings generated under `.NET 6.0`.
There is almost no change in binary file size after replacement.

### CODE REVIEW

**Comment by BruceChenQAQ** [comment]
There are a lot of changes, so it would be great if someone could come and help review the code or test it.

**Comment by Sergapr** [comment]
Hi! Thank u for ur help!
Will it help with AutoFish and BadPackets problem? Or not?

**Comment by milutinke** [comment]
> Hi! Thank u for ur help! Will it help with AutoFish and BadPackets problem? Or not?

Read his answer in the issue again and stick to the issue.

**Comment by BruceChenQAQ** [comment]
> > Hi! Thank u for ur help! Will it help with AutoFish and BadPackets problem? Or not?
> 
> Read his answer in the issue again and stick to the issue.

@Sergapr 
We need more information to diagnose the problem in the issue, see my response for details.
You can also find the notes for each configuration item in the [documentation](https://mccteam.github.io/guide/chat-bots.html#auto-fishing).

**Comment by Sergapr** [comment]
image
@BruceChenQAQ AutoFish crush not fixed bro, i cant use default sennings

**Comment by BruceChenQAQ** [comment]
> image @BruceChenQAQ AutoFish crush not fixed bro, i cant use default settings

Please upload `MinecraftClient.ini` as a file and not as text, I am currently unable to reproduce the issue.

**Comment by Sergapr** [comment]
> > image @BruceChenQAQ AutoFish crush not fixed bro, i cant use default settings
> 
> 
> 
> Please upload `MinecraftClient.ini` as a file and not as text, I am currently unable to reproduce the issue.

I am sorry, I can't do it right now. But I can say that all what I changed is 
EntnityHalndling true
Inventoryhandling true
AutoFish enabled true
Map true.

**Comment by BruceChenQAQ** [comment]
> 

I can get into the game normally using these settings, and I suspect that some invisible character in the config file is affecting the parsing.

**Comment by BruceChenQAQ** [comment]
> > > image @BruceChenQAQ AutoFish crush not fixed bro, i cant use default settings
> > 
> > 
> > Please upload `MinecraftClient.ini` as a file and not as text, I am currently unable to reproduce the issue.
> 
> I am sorry, I can't do it right now. But I can say that all what I changed is EntnityHalndling true Inventoryhandling true AutoFish enabled true Map true.

I can get into the game normally using these settings, and I suspect that some invisible character in the config file is affecting the parsing.

**Comment by Sergapr** [comment]
Give me some time. I'll record a video. 
I just download the latest version of MCC from Realises, open it, change some settings in .ini file  and after it have errors

**Comment by Sergapr** [comment]
https://user-images.githubusercontent.com/106835861/193534097-00283e17-78d4-44a0-972d-7d525b890511.mp4

I am downloaded latest MCC version

**Comment by milutinke** [comment]
> Autofish_Trim_Trim.mp4
> 
> @BruceChenQAQ I am downloaded latest MCC version but have this problem yet. I have no ideas why it happens

Which version of .NET Core are you running?
You can check by typing `dotnet sdk check`
I am unable to re-create this on .NET Core 6.0.401

**Comment by Sergapr** [comment]
image

**Comment by Sergapr** [comment]
Can u connect to my pc with AnyDesk and fix it pls?

**Comment by BruceChenQAQ** [comment]
Added more logs at `str2double`. Try using [this](https://github.com/BruceChenQAQ/Minecraft-Console-Client-1.19dev/releases/tag/20221003-54).

**Comment by Sergapr** [comment]
> Added more logs at `str2double`. Try using [this version](https://github.com/BruceChenQAQ/Minecraft-Console-Client-1.19dev/releases/tag/20221003-54) and posting the logs.

image

**Comment by BruceChenQAQ** [comment]
Try [this version](https://github.com/BruceChenQAQ/Minecraft-Console-Client-1.19dev/releases/tag/20221003-55)

**Comment by Sergapr** [comment]
image


>

**Comment by Sergapr** [comment]
image
Like this

**Comment by Sergapr** [comment]
image
But the BadPackets problem...
How can we fix it? I am really want to use a latest MCC version, but when i use it server kicks me.
If i use an old mcc version it is okay.

**Comment by BruceChenQAQ** [comment]
> Lol, i m replaced a "." to "," and it works!

Probably because the parser uses different separators in different languages.

**Comment by BruceChenQAQ** [comment]
> image But the BadPackets problem... How can we fix it? I am really want to use a latest MCC version, but when i use it server kicks me. If i use an old mcc version it is okay.

If you can find the earliest version of MCC where this problem occurred, we will be able to fix it more easily.

**Comment by Sergapr** [comment]
I'm glad we were able to fix this.

> > Lol, i m replaced a "." to "," and it works!
> 
> Probably because the parser uses different separators in different languages.

May be. 
I'm glad we were able to fix this.

**Comment by Sergapr** [comment]
> > image But the BadPackets problem... How can we fix it? I am really want to use a latest MCC version, but when i use it server kicks me. If i use an old mcc version it is okay.
> 
> If you can find the earliest version of MCC where this problem occurred, we will be able to fix it more easily.

Yes, sure, give me some time

**Comment by BruceChenQAQ** [comment]
> I'm glad we were able to fix this.
> 
> > > Lol, i m replaced a "." to "," and it works!
> > 
> > 
> > Probably because the parser uses different separators in different languages.
> 
> May be. I'm glad we were able to fix this.

Try [this version](https://github.com/BruceChenQAQ/Minecraft-Console-Client-1.19dev/releases/tag/20221003-56)

**Comment by Sergapr** [comment]
I am tested versions.
[The release](https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/20220903-37) works well, no any bugs, crush etc.
[The release](https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/20220905-41)  Problem when connecnitg to minigame
image
[The release](https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/20220905-42) works well, no any bugs and kicks.
[The release ](https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/20220906-43)
image
 crush when join game
[The release](https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/20220907-44) 
image simmilar problem, сrush when joining minigame
[The reseale ](https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/20220907-45)
image
Simmilar problem which i have now. BadPackets kick. I think it is because adding a /chunk command and it send packets even i dont use it.

**Comment by Sergapr** [comment]
If u can, create a release without "chunk" function, please. I belive that it is a reason of kicking

**Comment by milutinke** [comment]
> > Lol, i m replaced a "." to "," and it works!
> 
> Probably because the parser uses different separators in different languages.

It's the regional settings fault, that is the problem most likely, I remember having issues with toString with floats, it would print "," instead of ".".

**Comment by milutinke** [comment]
> > > Lol, i m replaced a "." to "," and it works!
> > 
> > 
> > Probably because the parser uses different separators in different languages.
> 
> It's the regional settings fault, that is the problem most likely, I remember having issues with toString with floats, it would print "," instead of ".".
Maybe we could add a custom function for parsing floats that would ignore if it is using , or .

**Comment by BruceChenQAQ** [comment]
> If u can, create a release without "chunk" function, please. I belive that it is a reason of kicking

The `/chunk` command does not send or change any packets sent to the server.
Test out that it's a terrain handling problem and you can turn off `terrainandmovements` and you won't get kicked out.

**Comment by Sergapr** [comment]
> > If u can, create a release without "chunk" function, please. I belive that it is a reason of kicking
> 
> 
> 
> The `/chunk` command does not send or change any packets sent to the server.
> 
> Test out that it's a terrain handling problem and you can turn off `terrainandmovements` and you won't get kicked out.

I am turned it off, but get kicked 😕

**Comment by Sergapr** [comment]
Can u reproduce a bug?

**Comment by Sergapr** [comment]
May be there are a function to listen a packets sending by mcc?

**Comment by BruceChenQAQ** [comment]
It seems to be a problem with inventory handling, which is no longer kicked out after ignoring `WindowConfirmation` packet.

**Comment by Sergapr** [comment]
> It seems to be a problem with inventory handling, which is no longer kicked out after ignoring `WindowConfirmation` packet.

But I can't join mini game and use autofish without inventory handling

**Comment by BruceChenQAQ** [comment]
@Sergapr 
Try [this release](https://github.com/BruceChenQAQ/Minecraft-Console-Client-1.19dev/releases/tag/20221003-57)

**Comment by Sergapr** [comment]
> @Sergapr Try [this release](https://github.com/BruceChenQAQ/Minecraft-Console-Client-1.19dev/releases/tag/20221003-57)

I cant belive... IT IS WOKS!!!
THANK YOU VERY MUCH BRO!
What was the problem?

**Comment by BruceChenQAQ** [comment]
lowered the value of `currentMovementSpeed` to 2. This is also likely to be the reason why other servers detect it as cheating.
Do not reply to `WindowConfirmation` packet when actionID is not legal.

**Pull request merged**
