### PR TITLE
Implemented the Follow Player chat bot.

### PR DESCRIPTION
**Pull request by milutinke**
Added an ability to follow the player using the `/follow` command as requested in #2125
Command usage: `/follow <player name|stop> [-f]`

NOTE: The bot sometimes can be a bit slow, we need to implement a method that can cancel the current Walking task, that would speed it up.
I've added a default update timer to make the bot a bit more faster, it does not go where it doesn't need to, we need to figure out what setting is the most optimal one.
Did some basic testing, seems that it is working as intended, haven't had any issues, as far as I am asked, it's ready to go, tho I want to get some feedback/ideas to improve it.

The video (Sorry for the bad quality an update to the OBS wiped my settings): 
https://streamable.com/g2gdl4

### CODE REVIEW

**Comment by Splarkszter** [comment]
How can i test this script?

**Comment by Splarkszter** [comment]
I think the bot should have this parameters:
- Threshold: How much the bot has to be from the current followed entity to stop walking, with both vertical and horizontal thresholds and with it's own update rate setting.
- Update rate: How often the path to the current followed entity is updated.

Update rate i think would be good to be between 100ms to 200ms default if it's not too heavy for the CPU, that will need to be tested. Maybe a more refined way is to choose from the last destination to reach to calculate the path and queue them (hopefully without memory leaks) so the bot does not stop walking unless it is inside the threshold.

Also, i don't know if those strange head movements can be fixed (But i think that is more for the TerrainAndMovements maintainer).

**Comment by milutinke** [comment]
> I think the bot should have this parameters:
> 
>     * Threshold: How much the bot has to be from the current followed entity to stop walking, with both vertical and horizontal thresholds and with it's own update rate setting.
> 
>     * Update rate: How often the path to the current followed entity is updated.
> 
> 
> Update rate i think would be good to be between 100ms to 200ms default if it's not too heavy for the CPU, that will need to be tested. Maybe a more refined way is to choose from the last destination to reach to calculate the path and queue them (hopefully without memory leaks) so the bot does not stop walking unless it is inside the threshold.
> 
> Also, i don't know if those strange head movements can be fixed (But i think that is more for the TerrainAndMovements maintainer).

It already does have those 2.

You can clone it and build it yourself, here is the manual:

Use this command for cloning instead the one from the documentation: https://mccteam.github.io/docs/guide/installation.html#building-from-the-source-code
```bash
git clone https://github.com/milutinke/Minecraft-Console-Client/ --recursive -b follow-player
```

**Comment by milutinke** [comment]
If there are no complaint or suggestions on improving, I'll be merging in few days, it's in a decent state.
We could improve it by improving the Terrain Handling code, like an ability to cancel a running task when a new one is needed.

**Pull request merged**
