### PR TITLE
Add "/chunk status" command. (For debugging)

### PR DESCRIPTION
**Pull request by BruceChenQAQ**
image

image

image

Usage:
``/chunk status``
``/chunk status [chunkX chunkZ|locationX locationY locationZ]`` // Mark the specified chunk
``/chunk <setloading|setloaded|delete> chunkX chunkZ`` // For debugging use
``/chunk <setloading|setloaded|delete> locationX locationY locationZ`` // For debugging use

### CODE REVIEW

**Comment by milutinke** [comment]
Is there a way to force the server to re-send chunks, like when pressing `F3 + A`.
(I still haven't gotten myself familiarized with this part of the code).

Asking because sometimes when you load new chunks as a different player,  they do not get loaded on the client and he can't walk there, at least that I've noticed from the latest tests.

**Comment by milutinke** [comment]
> Is it necessary to crop the unloaded chunks at the edges so that they have only 1 or 2 layers?
> 
> To support a larger chunk loading range, this requires getting the width and height of the terminal from ConsoleInteractive.

You could set like 2 static variables on the program with Console Interactive, and use them here.
When we do abstractions we can deal with them there.

**Comment by BruceChenQAQ** [comment]
> Is there a way to force the server to re-send chunks, like when pressing `F3 + A` in the official Java client (I still haven't gotten myself familiarized with this part of the code).

net/minecraft/client/Keyboard.java
```Java
private boolean processF3(int key) {
if (this.debugCrashStartTime > 0L && this.debugCrashStartTime < Util.getMeasuringTimeMs() - 100L) {
	return true;
} else {
    switch (key) {
        case 65:
            this.client.worldRenderer.reload();
            this.debugLog("debug.reload_chunks.message");
            return true;
    // ......
    }
}
```

net/minecraft/client/render/WorldRenderer.java
```Java
public void reload() {
  if (this.world != null) {
    this.reloadTransparencyShader();
    this.world.reloadColor();
    if (this.chunkBuilder == null) {
        this.chunkBuilder = new ChunkBuilder(this.world, this, Util.getMainWorkerExecutor(), this.client.is64Bit(), this.bufferBuilders.getBlockBufferBuilders());
    } else {
        this.chunkBuilder.setWorld(this.world);
    }

    this.shouldUpdate = true;
    this.cloudsDirty = true;
    this.builtChunks.clear();
    RenderLayers.setFancyGraphicsOrBetter(MinecraftClient.isFancyGraphicsOrBetter());
    this.viewDistance = this.client.options.getClampedViewDistance();
    if (this.chunks != null) {
        this.chunks.clear();
    }

    this.chunkBuilder.reset();
    synchronized(this.noCullingBlockEntities) {
        this.noCullingBlockEntities.clear();
    }

    this.chunks = new BuiltChunkStorage(this.chunkBuilder, this.world, this.client.options.getClampedViewDistance(), this);
    if (this.fullUpdateFuture != null) {
        try {
            this.fullUpdateFuture.get();
            this.fullUpdateFuture = null;
        } catch (Exception var3) {
            LOGGER.warn((String)"Full update failed", (Throwable)var3);
        }
    }

    this.renderableChunks.set(new RenderableChunks(this.chunks.chunks.length));
    this.chunkInfos.clear();
    Entity entity = this.client.getCameraEntity();
    if (entity != null) {
        this.chunks.updateCameraPosition(entity.getX(), entity.getZ());
    }
  }
}
```

It seems to be just a re-rendering of chunks and entities, etc.

**Comment by breadbyte** [comment]
> To support a larger chunk loading range, this requires getting the width and height of the terminal from ConsoleInteractive.

ConsoleInteractive simply uses the values in `Console.BufferWidth` for terminal length, and `Console.BufferHeight` for terminal height, but relying on this is problematic (in headless applications without a visual terminal; see issues with docker.)

I am interested to know why this is limited by the terminal height and width. Is this for showing the loaded chunk range visually?

**Comment by milutinke** [comment]
Yeah, I got confused for a sec.
I wonder why the client does not receive the newly loaded chunks.
I'll do some testing after this PR is merged, this will come in handy.

**Comment by milutinke** [comment]
> > To support a larger chunk loading range, this requires getting the width and height of the terminal from ConsoleInteractive.
> 
> ConsoleInteractive simply uses the values in `Console.BufferWidth` for terminal length, and `Console.BufferHeight` for terminal height, but relying on this is problematic (in headless applications without a visual terminal; see issues with docker.)
> 
> I am interested to know why this is limited by the terminal height and width. Is this for showing the loaded chunk range visually?

It will look broken on smaller screens.

**Comment by BruceChenQAQ** [comment]
> Asking because sometimes when you load new chunks as a different player, they do not get loaded on the client and he can't walk there, at least that I've noticed from the latest tests.

Does it mean that a newly loaded chunk by another player will not be sent to MCC?

**Comment by BruceChenQAQ** [comment]
> > To support a larger chunk loading range, this requires getting the width and height of the terminal from ConsoleInteractive.
> 
> ConsoleInteractive simply uses the values in `Console.BufferWidth` for terminal length, and `Console.BufferHeight` for terminal height, but relying on this is problematic (in headless applications without a visual terminal; see issues with docker.)
> 
> I am interested to know why this is limited by the terminal height and width. Is this for showing the loaded chunk range visually?

This is to be able to change the number of chunks displayed to avoid line breaks.

**Comment by milutinke** [comment]
> > Asking because sometimes when you load new chunks as a different player, they do not get loaded on the client and he can't walk there, at least that I've noticed from the latest tests.
> 
> Does it mean that a newly loaded chunk by another player will not be sent to MCC?

It seemed like that to me, I'll do more testing when I can.

**Comment by BruceChenQAQ** [comment]
image

**Comment by BruceChenQAQ** [comment]
> Is it necessary to crop the unloaded chunks at the edges so that they have only 1 or 2 layers?
> 
> To support a larger chunk loading range, this requires getting the width and height of the terminal from ConsoleInteractive.

The two functions mentioned have been implemented, is there anything else that needs to be changed?

**Comment by BruceChenQAQ** [comment]
Found a bug, fixing.

**Comment by BruceChenQAQ** [comment]
image

**Comment by BruceChenQAQ** [comment]
> > > Asking because sometimes when you load new chunks as a different player, they do not get loaded on the client and he can't walk there, at least that I've noticed from the latest tests.
> > 
> > 
> > Does it mean that a newly loaded chunk by another player will not be sent to MCC?
> 
> It seemed like that to me, I'll do more testing when I can.

What I remember is that the server sends chunk data to the player based on player location and rendering distance, so the player's chunk load will not be affected by another player.

**Comment by BruceChenQAQ** [comment]
All features are now available.
I will test it again tomorrow before merging it, or anyone else who wants to come and test it.
(*Sleeping)

**Pull request merged**
