### PR TITLE
[1.19] Added Entity, Block, Material and Item palettes, Enabled Entity and Inventory handling + Fixed a bug

### PR DESCRIPTION
**Pull request by milutinke**
Added Entity, Block, Material and Item palettes.
Fixed a bug in `SpawnEntity` packet which was causing crashes when Entity handling was enabled.
Temporarily disabled `BlockChanged` packet for 1.19 due to crashing (I am not familiar with Terrain and Movement Handling code).

Tested Auto Attack bot and inventory handling, it works, tho ASCII art is broken due to ConsoleInteractive.

### CODE REVIEW

**Comment by milutinke** [comment]
Forgot to mention that Terrain Handling does not work for 1.19.

**Comment by milutinke** [comment]
@ORelio Review this PR before #2123 in order not to get merge conflicts.

**Comment by milutinke** [comment]
Fixed #1632 and #1648, tested and works.

**Comment by milutinke** [comment]
Everything works here, can be merged.

**Review by ORelio — APPROVED** [review]
Looks good to me!

**Pull request merged**
