### PR TITLE
Implemented 1.20.2

### PR DESCRIPTION
**Pull request by milutinke**
Fully implemented 1.20.2, heavy code changes.
I am waiting for people to test it out and give me feedback before merging.

### CODE REVIEW

**Comment by Delivator** [comment]
```
Retrieving Server Info...
Server version : 1.20.2 (protocol v764)
Cached profile key is still valid for x.
[MCC] Version is supported.
Logging in...
[MCC] Checking Session...
[MCC] Server was successfully joined.
Type '/quit' to leave the server.
> Unhandled exception. System.IO.InvalidDataException: Failed to process incoming packet of type ChunkBatchFinished. (PacketID: 12, Protocol: 764, LoginPhase: False, InnerException: System.DivideByZeroException).
 ---> System.DivideByZeroException: Attempted to divide by zero.
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePlayPackets(Int32 packetId, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetId, Queue`1 packetData)
   --- End of inner exception stack trace ---
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetId, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by Delivator** [comment]
```
Minecraft Console Client v1.20.2 - for MC 1.4.6 to 1.20.2 - Github.com/MCCTeam
GitHub build 77, built on 2023-11-25 from commit eb7bfff
Resolving x..
Found server x for domain x
Help us translate MCC: https://crwd.in/minecraft-console-client
A new version of MCC is available and you can download it via /upgrade
Or download it manually: https://github.com/MCCTeam/Minecraft-Console-Client/releases
Cached session is still valid for x.
Retrieving Server Info...
Server version : 1.20.2 (protocol v764)
Cached profile key is still valid for x.
[MCC] Version is supported.
Logging in...
[MCC] Checking Session...
[MCC] Server was successfully joined.
Type '/quit' to leave the server.
> Unhandled exception. System.IO.InvalidDataException: Failed to process incoming packet of type ChunkBatchFinished. (PacketID: 12, Protocol: 764, LoginPhase: False, InnerException: System.DivideByZeroException).
 ---> System.DivideByZeroException: Attempted to divide by zero.
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePlayPackets(Int32 packetId, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetId, Queue`1 packetData)
   --- End of inner exception stack trace ---
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetId, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by milutinke** [comment]
> ```
> Minecraft Console Client v1.20.2 - for MC 1.4.6 to 1.20.2 - Github.com/MCCTeam
> GitHub build 77, built on 2023-11-25 from commit eb7bfff
> Resolving x..
> Found server x for domain x
> Help us translate MCC: https://crwd.in/minecraft-console-client
> A new version of MCC is available and you can download it via /upgrade
> Or download it manually: https://github.com/MCCTeam/Minecraft-Console-Client/releases
> Cached session is still valid for x.
> Retrieving Server Info...
> Server version : 1.20.2 (protocol v764)
> Cached profile key is still valid for x.
> [MCC] Version is supported.
> Logging in...
> [MCC] Checking Session...
> [MCC] Server was successfully joined.
> Type '/quit' to leave the server.
> > Unhandled exception. System.IO.InvalidDataException: Failed to process incoming packet of type ChunkBatchFinished. (PacketID: 12, Protocol: 764, LoginPhase: False, InnerException: System.DivideByZeroException).
>  ---> System.DivideByZeroException: Attempted to divide by zero.
>    at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePlayPackets(Int32 packetId, Queue`1 packetData)
>    at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetId, Queue`1 packetData)
>    --- End of inner exception stack trace ---
>    at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetId, Queue`1 packetData)
>    at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> ```

Can you give me the IP?

**Comment by Delivator** [comment]
Yeah sure `zaza.delivator.me` I will need to whitelist you, what's your MC Name?

**Comment by Delivator** [comment]
Or can I help debug somehow?

**Comment by milutinke** [comment]
> Yeah sure `zaza.delivator.me` I will need to whitelist you, what's your MC Name?

milutinke

**Comment by Delivator** [comment]
@milutinke added you. Running 1.20.2 vanilla straight from minecraft.net

**Comment by Delivator** [comment]
actually I created a copy of the server that you can test on, ip: `mc.delivator.me:25566`

**Comment by milutinke** [comment]
> actually I created a copy of the server that you can test on, ip: `mc.delivator.me:25566`

Thanks, I think it should be fixed now.

**Comment by Delivator** [comment]
> > actually I created a copy of the server that you can test on, ip: `mc.delivator.me:25566`
> 
> Thanks, I think it should be fixed now. https://github.com/milutinke/Minecraft-Console-Client/releases/tag/20231126-78

Yeah this works for me!

**Comment by brothanb** [comment]
> > > actually I created a copy of the server that you can test on, ip: `mc.delivator.me:25566`
> > 
> > 
> > Thanks, I think it should be fixed now. https://github.com/milutinke/Minecraft-Console-Client/releases/tag/20231126-78
> 
> Yeah this works for me!

FYI...  The build passes a smoke test on MacOS Ventura 13.6.1 on an i7 MBP.  I haven't tried much more than logging into a Paper 1.20.2 server...

**Comment by milutinke** [comment]
Alright, since no one has provided any more bugs, I'll merge the changes.

**Pull request merged**
