### PR TITLE
Option and Command to Disable Gravity

### PR DESCRIPTION
**Pull request by mvoppen**
Currently gravity is always active. But in real play there are many situations where no gravity is active. 

This PR creates an option to activate/deactivate gravity and extends the move command by two subcommands to activate/deactivate gravity.

### CODE REVIEW

**Review by ReinforceZwei — APPROVED** [review]

**Comment by ReinforceZwei** [comment]
Looks good to me. Thanks for your work. 

@ORelio are you okay with this PR?

**Comment by ORelio** [comment]
@ReinforceZwei Yes! Missed that PR, sorry.
@mvoppen Thanks for your contribution which can help on servers where flying is enabled.
I've adjusted the /move command compared to how you originally implemented it and added french translation as well.

I see two things that could be improved, if you have enough time:

1. Ideally, instead of a setting, gravity handling should be sourced from player capabilities (see #1508 and https://wiki.vg/Protocol#Player_Abilities_.28clientbound.29). The server sends a packet to the client to tell whether flying is enabled. MCC could read that packet and automatically (dis)able gravity handling accordingly.

2. Pathfinding would need to be adjusted as well to take flying into account. This can be done in CanMove() to allow moving up even when not on ground, IsSafe() to allow falling, and GetAvailableMoves() to allow normal movement in the air (enter the first if{ statement when gravity is not enabled). That should do the job but might require some more changes during testing.

Of course if you're busy I'm okay with the changes as is, so the pull request can be merged 😉

**Review by ORelio — APPROVED** [review]

**Comment by mvoppen** [comment]
There are two components in that flying topic. The server decides if the client is allowed to fly and the client decides if the player actually is flying. So anyway we need an internal flag or a setting if gravity is enabled. The server cannot decide that allone.

There are additional topics not implemented yet like swimming and floating water.

So my approach was to start it simple and have the option to disable gravity.

**Comment by ORelio** [comment]
Okay, let's keep it as is.

**Pull request merged**
