### PR TITLE
Turkish 'README' file. | Türkçe 'README' dosyası.

### PR DESCRIPTION
**Pull request by ByDexterTR**

### CODE REVIEW

**Comment by milutinke** [comment]
Thank you for your contribution.
We need someone to independently verify the correctness of this before merging.

**Comment by BruceChenQAQ** [comment]
Thank you for your contribution.
We are about to update this paragraph in the README, can you translate it as well by the way?
```markdown
## Translating Minecraft Console Client 🌍

Check out: [How to update or add translations for MCC](https://mccteam.github.io/guide/contibuting.html#translations).

MCC now supports the following languages (Alphabetical order) :
  * `de.ini` : Deutsch - German
  * `en.ini` : English - English
  * `fr.ini` : Français (France) - 	French
  * `ru.ini` : Русский (Russkiy) - Russian
  * `vi.ini` : Tiếng Việt (Việt Nam) - Vietnamese
  * `zh-Hans.ini` : 简体中文（中国大陆） - Chinese Simplified (China; Mandarin)
```

The content of that link has not been deployed yet and can be seen [here](https://github.com/BruceChenQAQ/MCCTeam.github.io/blob/master/source/guide/contibuting.md).

**Comment by ByDexterTR** [comment]
i will also make the new file and lang folder you sent but i need some time

**Comment by BruceChenQAQ** [comment]
If you are going to translate MCC, please use the ["lang" folder](https://github.com/MCCTeam/Minecraft-Console-Client/tree/brucechen-toml-config/MinecraftClient/Resources/lang) in [this branch](https://github.com/MCCTeam/Minecraft-Console-Client/tree/brucechen-toml-config).
We have added support for translating settings files, and many new entries have been added.
After testing, this branch will be merged into the main branch.

**Pull request closed without merging**
