### PR TITLE
Partial implementation for 1.19.3

### PR DESCRIPTION
**Pull request by milutinke**
I have implemented what I could within the time frame I had, I hope someone can take it over from here.
**The implementation of the chat is not complete.**
If I am not mistaken, messages now are stored in a single chain by their index, the code for storing and validating messages should be written for the new implementation.

**NOTE: Some packets that are marked with DONE have just the packet reading logic done, they might not be wired to work with other packets**

**When someone wants to take over this, merge the PR.**

Reference implementation:
https://github.com/adepierre/Botcraft/commit/f5b9032266a2eb8a296d73e5808f0c9666688d49
https://github.com/adepierre/Botcraft/commit/755009f07f75c5fb5cb885aa6eb88259e1559800

Less detailed (simple) overlay of what has changed:
```yaml
Clientbound packets:
- Chat Preview packet removed
- Profileless Chat Message packet added
- Message Header packer was removed
- Player Chat Message packet was changed (heavy changes)
- Server Data packet changed (Previews Chat field was removed)
- Entity Sound Effect changed (Seed field added)
- Feature Flags packed added

Serverbound packets:
- Message Acknowledgment packet changed completely
- Chat Command packet changed
- Chat Message packet changed
- Chat preview packet removed
- Player Session packet added
```

The detailed list of changes:
```yaml
C2S(login):

Login Start: (DONE)
- Has Sig Data
- Timestamp
- Public Key Length
- Public Key
- Signature Length
- Signature

Encryption Response: (DONE)
- Has Verify Token
- Optional Verify Token Length
+ Verify Token Length
- Optional Verify Token
+ Verify Token
- Optional Salt
- Optional Message Signature Length
- Optional Message Signature

S2C(play):
- Client Preview
- Custom Sound Effect
+ Profileless Chat Message (DONE)
- Message Header
+ Player Remove
- Set Display Chat Preview
+ Feature Flags (DONE)

Merchant Offers: (DONE)
- Has second item (this never existed, all Slot's start with a Present field that is what this was mistaken as)

Player Chat Message (This one has complex changes): (fields implemented, TODO: checking and acknowledgment and displaying)
- Message Signature Present
- Message Signature length
- Message Signature bytes
- Header signature length
+ Index
- Header signature bytes
+ Message Signature Present
+ Message Signature bytes
- Plain Message
- Formatted Message present
- Formatted Message
- Previous Messages -> UUID
- Previous Messages -> Message ID
- Filter Type mask length

Server Data: (DONE)
- Previews Chat

Set Experience (DONE):
+ Order of Total Experience changed or was wrong

Entity Sound Effect: (DONE)
+ Seed

C2S(play):
- Chat Preview
+ Player Session

Message Acknowledgment:
- Has Data
- Profile ID
- Last Signature Length
- Last Signature
+ Message Count

Chat Command:
- Signature length
- Signed Preview
+ Message Count
+ Acknowledged

Chat Message:
- Signature Length
+ Has Signature
- Signed Preview
- Array length
- Array of previously seen messages
- Previous message sender's ID.
- Messages Signature
- Has last message
- Last Message
- Messages signature
+ Message Count
+ Acknowledged
```

### CODE REVIEW

**Comment by ReinforceZwei** [comment]
What I have done:
```yaml
Packet Palette: done

S2C(play):
- Player Chat Message: partial done (TODO: signature verify, message index)
```
At this moment, client is possible to login and receive chat message. 

Sending message not yet done.

**Comment by ReinforceZwei** [comment]
Send and receive message without signing is functional. For cryptography part, I don't understand how it works or how to make it work, especially the `Acknowledged` BitSet field. So we might need @BruceChenQAQ again to help implementing the chat signing :pray:

```yaml
C2S(play):
- Chat Message: partial done (TODO: message signing)
- Chat Command: done
```

At this point, MCC can send and receive message on server with `enforce-secure-profile=false`.

**Comment by BruceChenQAQ** [comment]
It's partly done, the signature in the chat command is not yet complete.

**Comment by ReinforceZwei** [comment]
Seems like @BruceChenQAQ is finalizing this PR, I will stop here to prevent more code conflict :)

**Comment by BruceChenQAQ** [comment]
The above three commits are for:
```
C2S(play):
* Player Session: Done
* Chat Message: Done
* Chat Command: Done
* Message Acknowledgment: Done
S2C(play):
* Player Info: Done
* Chat Message: Partially completed, does not yet support verification of signatures.
* System Chat: Done
* Profileless Chat Message: Done
```

Next we need to make sure that all the other changes have been implemented and then merged into `brigadier-dev`.

**Comment by BruceChenQAQ** [comment]
There is a [message signing issue](https://github.com/MCCTeam/Minecraft-Console-Client/issues/2384#issuecomment-1396317436) on some servers but we are unable to reproduce it at the moment, I will merge this PR to synchronise the text resources on Crowdin as it has been lagging for almost two months.

**Pull request merged**
