### PR TITLE
Basic support for minecraft 1.19

### LINKED ISSUE #2053: [Idea] 1.19
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

1.19 support. Not much has changed as far as I know so its probably a hard coded prevention.

### Suggest a possible solution

_No response_

### Attach screenshot here (If applicable)

_No response_

### Minecraft Version

1.19

### Device

Raspberry Pi

### Operating System

Linux

### LINKED ISSUE #2079: [BUG] I can not connect to 1.19 Server
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19

### Console Client Version

Latest

### Expected Behavior

I was expecting for the Console Client to connect to the 1.19 server.

### Actual Behavior

Client 1.19 is not connecting to the server.
It says:
Server version : Purpur 1.19 (protocol v759)
Cannot connect to the server : This version is not supported !
Why can't it connect to 1.19 server? Is there a way to make it work?

### Steps to Reproduce the bug

1. 
2. 
3. 

### Attach screenshot here (If applicable)

a

### Anythings that could help diagnosing the bug

_No response_

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

play.craftkolik.com

### LINKED ISSUE #2085: [BUG] this version is not supported
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [x] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19

### Console Client Version

Latest

### Expected Behavior

i tried to connect to a minecraft server (version 1.19) but it did not let me it said Cannot connect to the server : This version is not supported ! i typed 1.19 in Server version but it still did not let me join

### Actual Behavior

it should let me join but it does not

### Steps to Reproduce the bug

1. idk
2. idk
3. idk

### Attach screenshot here (If applicable)

Screenshot (666)

### Anythings that could help diagnosing the bug

```txt
i don't know
```

### Device

Laptop

### Operating System

Windows

### Server Address (If applicable)

_No response_

### PR DESCRIPTION
**Pull request by BruceChenQAQ**
Support for signature and signature verification of chats.

Due to issue https://github.com/MCCTeam/Minecraft-Console-Client/issues/2082, MonoAesStream is currently used instead of RegularAesStream, which causes a certain amount of performance degradation.

Resolves #2053, resolves #2085, resolves #2079

### CODE REVIEW

**Comment by milutinke** [comment]
We did a great job, especially you.
What is left to be done, haven't been able to track every single thing?

**Comment by BruceChenQAQ** [comment]
> We did a great job, especially you. What is left to be done, haven't been able to track every single thing?

* Inventory, entity and terrain handling (it would be better to implement it after #1943 to be merged)
* Message previewing is not currently implemented
* The chat type should be read from the Registry Codec NBT Tag (contained in PacketTypesIn.JoinGame)
* ... Maybe there are more and I forgot about them?
* Part of the changes in 1.19.1 (wiki.vg is not yet updated)
  * Login Hello and Encrypted Response packets have changed
  * Chat: chat now consists of a message header and message body; chat signature section adds information about the last received chat
  * The "Type" field of the received chat messages has changed
  * Added packets for the new chat blocking feature
  * Added packet for synchronizing message acknowledgment

**Comment by milutinke** [comment]
> > We did a great job, especially you. What is left to be done, haven't been able to track every single thing?
> 
>     * Inventory, entity and terrain handling (it would be better to implement it after [Implemented Entity, Inventory, Block palettes and Terrain Handling for 1.17/.1 and 1.18/.1/.2 (Tested and working) #1943](https://github.com/MCCTeam/Minecraft-Console-Client/pull/1943) to be merged)
> 
>     * Message previewing is not currently implemented
> 
>     * The chat type should be read from the Registry Codec NBT Tag (contained in PacketTypesIn.JoinGame)
>       
>       * This NBT Tag is also related to terrain processing, which records the Y-axis range of all worlds in the server
> 
>     * ... Maybe there are more and I forgot about them?
> 
>     * Part of the changes in 1.19.1 (wiki.vg is not yet updated)
>       
>       * Login Hello and Encrypted Response packets have changed
>       * Chat: chat now consists of a message header and message body; chat signature section adds information about the last received chat
>       * The "Type" field of the received chat messages has changed
>       * Added packets for the new chat blocking feature
>       * Added packet for synchronizing message acknowledgment

I'll fork your branch after [Implemented Entity, Inventory, Block palettes and Terrain Handling for 1.17/.1 and 1.18/.1/.2 (Tested and working) #1943](https://github.com/MCCTeam/Minecraft-Console-Client/pull/1943) has been merged and then update the palettes on 1.19.
In the meantime, I'll research on 1.19.1 changes and write some pseudo code, or real code if I can.

**Comment by BruceChenQAQ** [comment]
> Oh yeah, we should generate keys for Mojang accounts.

The mojang account may not have access to the profile key now.

News from ATLauncher:
> **Jul 11, 2022 - Mojang Accounts Cannot Play Online Anymore**
> We're currently seeing multiple issues being raised where people can no longer login to online servers anymore with their non migrated Mojang account.
> It seems as though Microsoft has pulled the support for Mojang accounts and in order to play on online servers now, you must migrate your account to a Microsoft account as the legacy api's used for session management within the game no longer are working.
> This may just be a bug, but more than likely it's intentional and you'll no longer be able to login to online servers with Mojang accounts going forward.

**Comment by BruceChenQAQ** [comment]
> I'll fork your branch after [Implemented Entity, Inventory, Block palettes and Terrain Handling for 1.17/.1 and 1.18/.1/.2 (Tested and working) #1943](https://github.com/MCCTeam/Minecraft-Console-Client/pull/1943) has been merged and then update the palettes on 1.19. In the meantime, I'll research on 1.19.1 changes and write some pseudo code, or real code if I can.

I committed an update to the 1.19.1-dev branch, maybe you can continue from here:
https://github.com/BruceChenQAQ/Minecraft-Console-Client-1.19dev/commits/1.19.1-dev

Updated the packet pattle for 1.19.1, but now it is only able to log into the server in offline mode.

**Comment by BruceChenQAQ** [comment]
@milutinke 
More information about message signature at https://github.com/MCCTeam/Minecraft-Console-Client/discussions/2087

**Comment by Splarkszter** [comment]
[Sorry if this question does not belong here]

I know it says basic support but do scripts work on this one? I try to execute the 'sample-script.cs' from the "docs" but it says 'Empty path name is not legal. (Parameter 'path')' and a bunch of text that i won't write rn because i feel it unneccesary.

**Comment by BruceChenQAQ** [comment]
@Splarkszter 
> I try to execute the 'sample-script.cs' from the "docs" but it says 'Empty path name is not legal. (Parameter 'path')' and a bunch of text that i won't write rn because i feel it unneccesary.

I tried to run a C# script and found that it works fine.
Can you provide more information about the script file path and the command you executed?

**Comment by Splarkszter** [comment]
https://imgur.com/a/gfvgFS5

 i get that. writing '/script helloworld' does the same

**Comment by BruceChenQAQ** [comment]
@Splarkszter 

This issue should be fixed in https://github.com/MCCTeam/Minecraft-Console-Client/pull/2061

Since the pull request is not currently merged, you can build the project yourself or download the .zip release from https://github.com/BruceChenQAQ/Minecraft-Console-Client-1.19dev/releases/tag/1.19.

**Comment by Splarkszter** [comment]
Thanks. Downloading the .zip instead of the .exe directly, fixed it.

**Comment by ORelio** [comment]
Hi @BruceChenQAQ, @Splarkszter, congrats for your work, this is a very big PR 🥇 👏
I scrolled through the changes and they look good to me. I'll merge the PR 👍

**Comment by milutinke** [comment]
Wrong mention xD
By the way #1943 should've been merged first, since there is a bunch of conflicts now.

**Pull request merged**
