### PR TITLE
Map Chat Bot

### PR DESCRIPTION
**Pull request by milutinke**
**Finally,**

Made a chat bot that can render maps.
The main purpose of this chat bot for the time being is to enable people to **solve captchas** on servers which use maps for verification.

**Current limitations:**

Since I was not able to find proper color mappings for the maps, the colors are not like in Minecraft and are weird and are looking ugly, but they do the job. I'll continue the search for the color mappings, and I'll take a look at the source code of the game too.

**Current feature set:**
- Render maps (*obviously*)
- Option to resize the rendered maps (*The default one is 128x128, quite small. The resizing cuts on quality, but can be useful*) (*Disabled by default*)
- Option to automatically render maps as they're received (*This can help with servers where the time to solve is really short*) (*Disabled by default*)
- Option to get notified when a map has been received (*Disabled by default*)
- Option to delete all rendered maps when closing the client or unloading the bot (*Enabled by default*)

**PS:**
There are some parts of the code which are commented out, they will be used once we have the right color mappings, please do not remove them.
Also, I haven't bothered with implementing icons, since they're useless for this use case.

**Example of the bot in action:**
image
image

### CODE REVIEW

**Comment by DevBobcorn** [comment]
I've done a bit research about it and found the problem. Actually, the map color dictionary is correct, but the colors are indexed with base color ids and not shade ids, while MC servers send shade ids, so a simple solution would be like:
```csharp
        public static ColorRGBA ColorByteToRGBA(byte receivedColorId)
        {
            byte baseColorId = (byte)(receivedColorId >> 2); // Divide received color id by 4 to get the base color id

            // Any new colors that we haven't added will be purple like in the missing CS: Source Texture
            if (!Colors.ContainsKey(baseColorId))
                return new ColorRGBA { R = 248, G = 0, B = 248, A = 255, Unknown = true };

            byte shadeId = (byte)(receivedColorId % 4);
            byte shadeMultiplier = 255;

            switch (shadeId)
            {
                case 0:
                    shadeMultiplier = 180;
                    break;

                case 1:
                    shadeMultiplier = 220;
                    break;

                case 3:
                    // NOTE: If we ever add map support below 1.8, this needs to be 220 before 1.8
                    shadeMultiplier = 135; 
                    break;
            }

            return new ColorRGBA
            {
                R = (byte)((Colors[baseColorId][0] * shadeMultiplier) / 255),
                G = (byte)((Colors[baseColorId][1] * shadeMultiplier) / 255),
                B = (byte)((Colors[baseColorId][2] * shadeMultiplier) / 255),
                A = 255
            };
        }
```
And here's what I get, which looks pretty much the same as it is in the game:
图片

**Comment by milutinke** [comment]
> I've done a bit research about it and found the problem. Actually, the map color dictionary is correct, but the colors are indexed with base color ids and not shade ids, while MC servers send shade ids, so a simple solution would be like:
> 
> ```cs
>         public static ColorRGBA ColorByteToRGBA(byte receivedColorId)
>         {
>             byte baseColorId = (byte)(receivedColorId >> 2); // Divide received color id by 4 to get the base color id
> 
>             // Any new colors that we haven't added will be purple like in the missing CS: Source Texture
>             if (!Colors.ContainsKey(baseColorId))
>                 return new ColorRGBA { R = 248, G = 0, B = 248, A = 255, Unknown = true };
> 
>             byte shadeId = (byte)(receivedColorId % 4);
>             byte shadeMultiplier = 255;
> 
>             switch (shadeId)
>             {
>                 case 0:
>                     shadeMultiplier = 180;
>                     break;
> 
>                 case 1:
>                     shadeMultiplier = 220;
>                     break;
> 
>                 case 3:
>                     // NOTE: If we ever add map support below 1.8, this needs to be 220 before 1.8
>                     shadeMultiplier = 135; 
>                     break;
>             }
> 
>             return new ColorRGBA
>             {
>                 R = (byte)((Colors[baseColorId][0] * shadeMultiplier) / 255),
>                 G = (byte)((Colors[baseColorId][1] * shadeMultiplier) / 255),
>                 B = (byte)((Colors[baseColorId][2] * shadeMultiplier) / 255),
>                 A = 255
>             };
>         }
> ```
> 
> And here's what I get, which looks pretty much the same as it is in the game: 图片

Oh, so that explains it, awesome.
Thank you very much. 🎉

**Comment by Sergapr** [comment]
That's very cool!
Thank u very much for your job!
It is possible to show this png in console?

**Comment by milutinke** [comment]
> That's very cool! Thank u very much for your job! It is possible to show this png in console?

Unfortunately it is not.

**Comment by milutinke** [comment]
The PR is ready for merge, I'll leave it for a bit for potential feedback.

**Comment by milutinke** [comment]
@Lord420123 Now you can enter that one server with captchas.

**Comment by kvr25565** [comment]
Good job!

**Comment by milutinke** [comment]
Not for future updates, the colors in the game code are located in:
`net\minecraft\world\level\material\MaterialColor.java`

**Comment by milutinke** [comment]
> That's very cool! Thank u very much for your job! It is possible to show this png in console?

Actually it might be possible after the ConsoleInteractive update, we're discussing this feature right now.

**Comment by Sergapr** [comment]
@milutinke i am sorry, i am really noob, but can i use it now? How to install it?

**Comment by milutinke** [comment]
> @milutinke i have a problem when /script map.cs image

You can't run it as a script, it's an integrated bot.
Wait for it to be merged.

**Comment by Sergapr** [comment]
> > @milutinke i have a problem when /script map.cs image
> 
> 
> 
> You can't run it as a script, it's an integrated bot, unless you change it not to use the translations and the settings api and to add the meta section to the cs file.
> 
> Wait for it to be merged.

Ok) it's worth it :D
Thank you!

**Comment by Sergapr** [comment]
@milutinke problem when joining server 
image

**Comment by Sergapr** [comment]
image
It is kicks a bot after install a latest realese.
On MCC version Minecraft Console Client v1.18.1 - for MC 1.4.6 to 1.18.1 work perfect, but there are no Map.cs(

**Comment by milutinke** [comment]
> image It is kicks a bot after install a latest realese. On MCC version Minecraft Console Client v1.18.1 - for MC 1.4.6 to 1.18.1 work perfect, but there are no Map.cs(

I am getting kicked in normal Minecraft, the server thinks that I'm a bot.
image

**Comment by Sergapr** [comment]
> > image It is kicks a bot after install a latest realese. On MCC version Minecraft Console Client v1.18.1 - for MC 1.4.6 to 1.18.1 work perfect, but there are no Map.cs(
> 
> 
> 
> I am getting kicked in normal Minecraft, the server thinks that I'm a bot.
> 
> image
> 
> 
Servers AntiCheat kicks me with reason"Bad packets"
If I connect with similar Minecraft version on this server it work correctly.

**Comment by milutinke** [comment]
> > > image It is kicks a bot after install a latest realese. On MCC version Minecraft Console Client v1.18.1 - for MC 1.4.6 to 1.18.1 work perfect, but there are no Map.cs(
> > 
> > 
> > I am getting kicked in normal Minecraft, the server thinks that I'm a bot.
> > image
> 
> Servers AntiCheat kicks me with reason"Bad packets" If I connect with similar Minecraft version on this server it work correctly.

Use a newer version then, no idea why that is happening, either it's a bad packet on 1.16.5 or some if their plugins have a bug.
It would be a lot of work and painful to discover which packet is faulty.

**Comment by Sergapr** [comment]
> > > > image It is kicks a bot after install a latest realese. On MCC version Minecraft Console Client v1.18.1 - for MC 1.4.6 to 1.18.1 work perfect, but there are no Map.cs(
> 
> > > 
> 
> > > 
> 
> > > I am getting kicked in normal Minecraft, the server thinks that I'm a bot.
> 
> > > image
> 
> > 
> 
> > Servers AntiCheat kicks me with reason"Bad packets" If I connect with similar Minecraft version on this server it work correctly.
> 
> 
> 
> Use a newer version then, no idea why that is happening, either it's a bad packet on 1.16.5 or some if their plugins have a bug.
> 
> It would be a lot of work and painful to discover which packet is faulty.

It kicks even I use 1.18
But if I use old MCC version I can connect with any version and it work correctly.

**Comment by milutinke** [comment]
> > > > > image It is kicks a bot after install a latest realese. On MCC version Minecraft Console Client v1.18.1 - for MC 1.4.6 to 1.18.1 work perfect, but there are no Map.cs(
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > I am getting kicked in normal Minecraft, the server thinks that I'm a bot.
> > 
> > 
> > > > image
> > 
> > 
> > > 
> > 
> > 
> > > Servers AntiCheat kicks me with reason"Bad packets" If I connect with similar Minecraft version on this server it work correctly.
> > 
> > 
> > Use a newer version then, no idea why that is happening, either it's a bad packet on 1.16.5 or some if their plugins have a bug.
> > It would be a lot of work and painful to discover which packet is faulty.
> 
> It kicks even I use 1.18 But if I use old MCC version I can connect with any version and it work correctly.

For me it works on 1.18, no idea why that is happening.
Maybe they logged your ip and don't let you in or the server software is not vanilla/notchian.

**Comment by Sergapr** [comment]
> > > > > > image It is kicks a bot after install a latest realese. On MCC version Minecraft Console Client v1.18.1 - for MC 1.4.6 to 1.18.1 work perfect, but there are no Map.cs(
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > I am getting kicked in normal Minecraft, the server thinks that I'm a bot.
> 
> > > 
> 
> > > 
> 
> > > > > image
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Servers AntiCheat kicks me with reason"Bad packets" If I connect with similar Minecraft version on this server it work correctly.
> 
> > > 
> 
> > > 
> 
> > > Use a newer version then, no idea why that is happening, either it's a bad packet on 1.16.5 or some if their plugins have a bug.
> 
> > > It would be a lot of work and painful to discover which packet is faulty.
> 
> > 
> 
> > It kicks even I use 1.18 But if I use old MCC version I can connect with any version and it work correctly.
> 
> 
> 
> For me it works on 1.18, no idea why that is happening.
> 
> Maybe they logged your ip and don't let you in or the server software is not vanilla/notchian.

Why it works correctly on old MCC version?

**Comment by Paradist** [comment]
Greetings, I have a little problem here. On versions 1.17.1 and above everything is fine, but for example already on 1.16.5 map can not get. 
"[ERROR] OnMapData: Got error from MinecraftClient.ChatBots.Map: System.ArgumentException: Parameter is not vali    at MinecraftClient.ChatBots.Map.OnMapData(Int32 mapid, Byte scale, Boolean trackingPosition, Boolean locked, List`1     at MinecraftClient.McClient.DispatchBotEvent(Action`1 action, IEnumerable`1 botList)rs)"

**Comment by Sergapr** [comment]
> Greetings, I have a little problem here. On versions 1.17.1 and above everything is fine, but for example already on 1.16.5 map can not get. 
> 
> `[ERROR] OnMapData: Got error from MinecraftClient.ChatBots.Map: System.ArgumentException: Parameter is not vali    at MinecraftClient.ChatBots.Map.OnMapData(Int32 mapid, Byte scale, Boolean trackingPosition, Boolean locked, List1     at MinecraftClient.McClient.DispatchBotEvent(Action1 action, IEnumerable1 botList)rs)`
> 
> 
I have similar problem, I am just using 1.18 Minecraft version

**Comment by milutinke** [comment]
Can't re create.
No idea why that is happening, the log is also not full.

**Comment by Sergapr** [comment]
> 

Try join HolyWorld server with 1.16.5

**Comment by milutinke** [comment]
> > 
> 
> Try join HolyWorld server with 1.16.5

Should be fixed now. Try the latest version.
Thanks to Bruce.

**Comment by pipi337** [comment]
Как сделать показ карты в дискорде

**Comment by milutinke** [comment]
> Как сделать показ карты в дискорде
> 

You need to first connect and activate the Discord Chat Bot, and then you can enable the Map Chat Bot Discord feature.
Read the documentation: https://mccteam.github.io/guide/chat-bots.html#discord-bridge

**Pull request merged**
