### PR TITLE
Allow newer SSL/TLS protocol versions

### PR DESCRIPTION
**Pull request by Daenges**
Fixes [this issue](https://github.com/MCCTeam/Minecraft-Console-Client/discussions/1885#discussioncomment-3434649).

### CODE REVIEW

**Comment by ORelio** [comment]
Would you mind adding a check so that the fix is only applied when launching the script using Mono?

**Comment by haventhadadonutyet** [comment]
This works! - Question though, is it possible to have it relay messages only if there is a word match? Like, messages without a sender, such as custom messages from the server?

**Comment by Daenges** [comment]
@ORelio the error appeared on a Windows 10 machine. There was no mono installed.

**Comment by milutinke** [comment]
> @ORelio the error appeared on a Windows 10 machine. There was no mono installed.

Since .NET 5.0 mono is no longer required, neither it works.

**Comment by Daenges** [comment]
@milutinke I tried to execute this script on the most recent build and it failed to compile. To verify this issue I downloaded an [older build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/20220506-20). So they might be using the 4.8 Framework version.

**Comment by Daenges** [comment]
> Like, customchatdetection but only if a certain word or phrase is included

@haventhadadonutyet You can try to work with the ping system, so you actually get notified if the message contains a certain phrase. Or you try around with [Chatformats](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/Resources/config/MinecraftClient.ini#L94) and regular expressions to find messages with certain phrases.

**Comment by ORelio** [comment]
> > @ORelio the error appeared on a Windows 10 machine. There was no mono installed.

> Since .NET 5.0/6.0 port, mono is no longer required, neither it works.

Oh, OK. This is weird because on .NET 5+ you should not need to manually set the TLS protocols like in .NET 4
Maybe the issue is related to this hotfix here that is likely no longer required:
https://github.com/MCCTeam/Minecraft-Console-Client/blob/bb4c13168beaefb278d21140f3ae56ef788b8b00/MinecraftClient/Protocol/ProxiedWebRequest.cs#L127

**Comment by Daenges** [comment]
@ORelio as I mentioned [here](https://github.com/MCCTeam/Minecraft-Console-Client/pull/2114#issuecomment-1221370815) it is very likely that they didn't use the new .NET build, as the script is not working in it.

**Comment by ORelio** [comment]
> @ORelio as I mentioned [here](https://github.com/MCCTeam/Minecraft-Console-Client/pull/2114#issuecomment-1221370815) it is very likely that they didn't use the new .NET build, as the script is not working in it.

OK so this is a fix for use with legacy builds. Okay, merging the PR.

**Pull request merged**
