### PR TITLE
Support for using relative coordinates in /move

### LINKED ISSUE #724: Support for use of relative coordinates in /move?
Hi,

What changes would need to happen to support the use of relative coordinates in the /move command, similar to this syntax in Minecraft's /teleport?
`/tp @s ~100 ~2.5 ~-10` where the player is teleported 100 blocks east of his current position, 2.5 block up, and 15 blocks north.

I'm sure something similar can be done with `/move getpos` and subtracting from the output of that, but relative coordinates would allow for easier scripting to have the bot move in a certain direction on a loop, and potentially a lot easier to handle for MCC-users with minimal knowledge of C#.

### PR DESCRIPTION
**Pull request by BruceChenQAQ**
resolve #724

Usage:
``/move 1 2 3``
``/move 1.23 4.56 7.89``
``/move ~5 ~1 ~-7``
``/move ~.2 ~.5 ~-.67``
``/move ~.2 63.5 ~-.67``

### CODE REVIEW

**Comment by BruceChenQAQ** [comment]
Tested it for a while and it worked as intended.
I will merge it, a small enhancement.

**Comment by milutinke** [comment]
When using the dot, I get an output that the chunk is not loaded.
image

**Comment by BruceChenQAQ** [comment]
> When using the dot, I get an output that the chunk is not loaded.

Tested at similar coordinates but I wasn't able to reproduce the problem
I'm working on adding a command that shows the chunk loading status to help debug this issue.

**Comment by BruceChenQAQ** [comment]
<details>
  <summary>Pictures</summary>

image
image

</details>

Implemented in https://github.com/BruceChenQAQ/Minecraft-Console-Client-1.19dev/commit/6430f13d3eb2288ce08800e39f8ac89c7f5b12fb.

Usage:
``/chunk status``
``/chunk <setloading|setloaded|delete> chunkX chunkZ``
``/chunk <setloading|setloaded|delete> locationX locationY locationZ``

**Comment by milutinke** [comment]
Awesome

**Comment by BruceChenQAQ** [comment]
PR: #2158

**Pull request merged**
